@startuml trabalho 17
left to right direction
skinparam packageStyle rectangle

actor Cliente as C
actor Sistema_de_Pagamento as SP
actor Estoque as E
actor Transportadora as T

rectangle " Sistema de Loja Online" {
    usecase "Selecionar Produto" as P1
    usecase "Comprar Produto" as P2
    usecase "Processar Pagamento" as P3
    usecase "Conferir estoque" as P4
    usecase "Realizar entrega" as P6

}

C --> P1
P1 ..> P2 : <<include>>
P3 <--- SP
P4 <--- E
P6 <--- T
P3 --> E
P4 --> T
P2 --> SP




@enduml